### ISSUE TITLE
Remove flooding log file pattern for push helpers

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-app-launch#12]
Currently any output of a push helper process is logged into a log file with the pattern `untrusted-helper-push-helper:<unique_number>:<appid>.log`
(At least seen on TELEports)
The issue here is that those files are never cleaned up by logrotate since they contain a unique number which makes logrotate think that those are indeed independent files.
So far it was not an issue since the push helpers of TELEports and Fluffychat did not log anything, but recently a Telegram server change made the pushhelper to log an error. Some users have hundreds of those files in their .cache directory, maybe even thousands.

**Comment by Flohack74** [comment]
Fact: This comes from the upstart job definition for pushhelpers, and tries to ensure a unique name and log file. So this must be fixed in the logrotate config which does not seem to work.

**Comment by NeoTheThird** [comment]
Were you planning to fix this in time for OTA-11? No pressure, just for planning.

**Comment by Flohack74** [comment]
I was planning to do this. However, it might be even behaving correctly, I just need more feeback if those logfiles are really persisted or deleted after 2 days or so. Will ask testers...

**Comment by NeoTheThird** [comment]
Okay. But we won't halt freezing for this, right? Though you still have at least a week, i think.

**Comment by Flohack74** [comment]
No, we wont halt, its basically not a critical fix, needs just investigation.

**Comment by Flohack74** [comment]
Closing this for now, seems it works as expected. Kinda false alarm...
